site_name: Markdown WaveDrom Example
repo_url: https://github.com/MaximilianKoestler/markdown-wavedrom-mkdocs-example
repo_name: Sources on GitHub

theme:
  name: material

markdown_extensions:
  - admonition
  - markdown_wavedrom
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/2.6.8/wavedrom.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/wavedrom/2.6.8/skins/default.js
  - js/wavedrom_loader.js
